#!/usr/bin/env bash
# Bash script that will display information about subdomains.
#Accept 2 args domain and subdomain
#When domain only provided, display information of all subdomain

dns_info ()
{
	record_type=$(dig "$2.$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
	ip_address=$(dig "$2.$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
	echo "The subdomain $2 is a $record_type record and points to $ip_address"

}


if [ "$#"  == 1 ]
then
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"
	do

		dns_info "$1" "$subdomain"

	done




elif [ "$#"  == 2 ] 
then
	 dns_info "$1" "$2"

fi
