#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
cd /var/www/
sudo chmod 777 html
echo 'Hello World!' > html/index.html
sudo chmod 755 html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
