#!/usr/bin/env bash
# install nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
chmod -R 755 /var/www/
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i "25i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
