#!/usr/bin/env bash
#Fix Ubuntu container’s Nginx installation not listening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart 
