#!/usr/bin/env bash
#Bash script that gives you information about the school file.
#Use if and, else (case is forbidden)
#Script should check if the file exists and print school file exists
#if file does not exist print school file does not exist
#If file exists print
#if the file is empty: school file is empty
#if the file is not empty: school file is not empty
#if the file is a regular file: school is a regular file
#if the file is not a regular file: (nothing)



if [ -e "school" ]
then
	echo "school file exists"

	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
