#!/usr/bin/env bash
#Bash script configures an Ubuntu server with requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8


#creating a copy of /etc/hosts
cp /etc/hosts ~/temp

echo "127.0.0.2	localhost" > ~/temp
echo "8.8.8.8	facebook.com" >> ~/temp
cp -f ~/temp /etc/hosts


