#!/usr/bin/env bash
# script that creates an RSA key pair.
# number of bits 4096  private key must be school
# created key must be protected by the passphrase betty
# Name of  private 
ssh-keygen -b 4096 -P betty -f school
